### ISSUE TITLE
Pip install torpeewee packages from pypi failed

### ISSUE THREAD

**Issue by cxyfreedom** [snower/torpeewee#1]
$ pip install torpeewee
Could not find a version that satisfies the requirement torpeewee (from versions: )
No matching distribution found for torpeewee

$ pip search torpeewee
torpeewee (0.0.1)  - Tornado asynchronous ORM by peewee

But if I install this packages from source, the versions is 0.0.3

**Comment by snower** [comment]
Sorry, I forget to upload the package file.
Fixed, you can retry.
Thanks.
